# Generated by Django 2.1.2 on 2020-04-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default='company_address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='company_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='company_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default='company_name', on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='vacancy_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=5000),
        ),
    ]
